name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    strategy:
      fail-fast: true
      matrix:
        alpine: ['3.19']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push alpine${{ matrix.alpine }}
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          outputs: type=registry,oci-mediatypes=true
          tags: |
            arukiidou/openvpn-docker:alpine${{ matrix.alpine }}
            arukiidou/openvpn-docker:latest
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: arukiidou/openvpn-docker
      - name: List tags
        run: docker image ls
